using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharpInNutShell.Chipter3
{
    internal class PartialClass
    {
        /*****
         * 
         * Partial types allow a type definition to be split—typically across multiple files. 
         * A common scenario is for a partial class to be autogenerated from some other source (such as a Visual Studio template or designer), and for that class to be augmented with additional hand-authored methods:
         * 
         * 
         * ****/


        // paymentfrom is partial Classes 
    }

    
}
