using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharpInNutShell.Chipter3
{
    partial class PaymentForm  // In auto-generated file
    {

        /***
         * 
         * Each participant must have the partial declaration; the following is illegal:
         * partial class PaymentForm {}
         * class PaymentForm {}
         * 
         * **/


        /***
         * 
         * Participants cannot have conflicting members. A constructor with the same parameters, for instance, cannot be repeated.
         * Partial types are resolved entirely by the compiler, which means that each participant must be available at compile time and must reside in the same assembly. 
         * You can specify a base class on one or more partial class declarations, as long as the base class, if specified, is the same. In addition, each participant can independently specify interfaces to implement.
         * 
         * We cover base classes and interfaces in “Inheritance” and “Interfaces.”
         * 
         * 
         * **/

        /***
         * 
         * partial type can contain partial methods. These let an autogenerated partial type provide customizable hooks for manual authoring;
         * 
         * **/

        partial void ValidatePayment(decimal amount);



    }
}
